# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-03 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(verbose_name='Data de Término')),
            ],
            options={
                'verbose_name': 'Safra',
                'ordering': ['name'],
                'verbose_name_plural': 'Safras',
            },
        ),
        migrations.CreateModel(
            name='PriceProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_created=True, verbose_name='Data de Criação')),
                ('average_price', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Preço Médio')),
            ],
            options={
                'verbose_name': 'Preço Médio',
                'ordering': ['creation_date'],
                'verbose_name_plural': 'Preços Médio',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Safra',
                'ordering': ['name'],
                'verbose_name_plural': 'Safras',
            },
        ),
        migrations.CreateModel(
            name='ProductService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Preço Médio')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvest.Product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Produto do Serviço',
                'ordering': ['amount'],
                'verbose_name_plural': 'Produtos do Serviço',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(verbose_name='Data de Término')),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvest.Harvest', verbose_name='Safra')),
                ('products', models.ManyToManyField(to='harvest.ProductService', verbose_name='Produtos Utilizados')),
            ],
            options={
                'verbose_name': 'Serviço',
                'ordering': ['name'],
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.AddField(
            model_name='priceproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvest.Product', verbose_name='Produto'),
        ),
    ]
