# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-03 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='products',
        ),
        migrations.AddField(
            model_name='productservice',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='harvest.Service', verbose_name='Serviço'),
            preserve_default=False,
        ),
    ]
