# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-04 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0003_auto_20170204_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13, verbose_name='Custo Total'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='priceproduct',
            name='creation_date',
            field=models.DateField(auto_created=True, auto_now_add=True, verbose_name='Data de Criação'),
        ),
    ]
