# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-04 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0004_auto_20170204_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weigh_price',
            field=models.FloatField(default=1, verbose_name='Valor Relevância(ponderador)'),
            preserve_default=False,
        ),
    ]
