# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-04 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0006_auto_20170204_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priceproduct',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Preço Médio', 'verbose_name_plural': 'Preços Médio'},
        ),
        migrations.AlterField(
            model_name='priceproduct',
            name='creation_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Data de Criação'),
        ),
    ]
